document.writeln("<div class=\'wrapper headwrapper\'>");
document.writeln("	<div class=\'logo_wrapper\'>");
document.writeln("		<div class=\'header_top\'>");
document.writeln("			<a href=\'http://47.94.95.194\' class=\'logo\' title=\'一心一益\' target=\'_blank\'></a>");
document.writeln("			<a href=\'/\' class=\'logo\' title=\'青蚨集团\'></a>");
document.writeln("			<a href=\'http://www.cnqingfu.com\' class=\'logo\' title=\'青蚨资产\' target=\'_blank\'></a>");
document.writeln("			<a href=\'http://www.qingfuzaixian.com\' class=\'logo\' title=\'青蚨在线\' target=\'_blank\'></a>");
document.writeln("		</div>");
document.writeln("	</div>	");
document.writeln("	<div class=\'header clearfix\'>");
document.writeln("		<div class=\'f-fl\'>");
document.writeln("			<a class=\'head-logo\' href=\'javaScript:;\'></a>");
document.writeln("		</div>");
document.writeln("		<ul class=\'nav f-fr\'>");
document.writeln("			<li><a href=\'/\'>首页</a></li>");
document.writeln("			<li>");
document.writeln("				<a href=\'javaScript:;\'>关于我们</a>");
document.writeln("				<div class=\'nav-body\'>");
document.writeln("					<ul class=\'nav-main clearfix\'>");
document.writeln("						<li><a href=\'../aboutUS.html\'>集团简介</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>			");
document.writeln("			<li>");
document.writeln("				<a href=\'javaScript:;\'>集团板块</a>");
document.writeln("				<div class=\'nav-body\'>");
document.writeln("					<ul class=\'nav-main clearfix\'>");
document.writeln("							<li><a href=\'../financial.html\'>青蚨金融</a></li>");
document.writeln("							<li><a href=\'../catering.html\'>青蚨餐饮</a></li>");
document.writeln("							<li><a href=\'../community.html\'>青蚨社区</a></li>");
document.writeln("							<li><a href=\'../education.html\'>青蚨教育</a></li>");
document.writeln("							<li><a href=\'../movie.html\'>青蚨影视</a></li>");
document.writeln("							<li><a href=\'../health.html\'>青蚨健康</a></li>");
document.writeln("							<li><a href=\'../gongyi.html\'>青蚨公益</a></li>					");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a href=\'javaScript:;\'>集团动态</a>");
document.writeln("				<div class=\'nav-body\'>");
document.writeln("					<ul class=\'nav-main clearfix\'>");
document.writeln("						<li><a href=\'../gonggao.html\'>重要公告</a></li>");
document.writeln("						<li><a href=\'../dongtai.html\'>集团动态</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li><a href=\'../duty.html\'>企业公民</a></li>");
document.writeln("			<li class=\'nav-last\'><a href=\'../connectUS.html\'>联系我们</a></li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</div>");