document.writeln("<header>");
document.writeln("		<div class=\'header-inner\'>");
document.writeln("			<div class=\'head-logo\'>");
document.writeln("				<a href=\'home.html\'><img src=\'../images/common/logo.png\' alt=\'\'></a>");
document.writeln("			</div>");
document.writeln("			<div class=\'menu-icon\'></div>");
document.writeln("		</div>		");
document.writeln("		<div class=\'menu-box\'>");
document.writeln("			<ul class=\'menu-list\'>");
document.writeln("				<li><a href=\'home.html\'>首页</a></li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javaScript:;\'>关于我们</a>");
document.writeln("					<i class=\'ico\'></i>");
document.writeln("					<div class=\'menuson\'>");
document.writeln("						<a href=\'about.html\'>集团简介</a>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("				    <a href=\'javaScript:;\'>集团板块</a>");
document.writeln("				    <i class=\'ico\'></i>");
document.writeln("					<div class=\'menuson\'>");
document.writeln("						<a href=\'financial.html\'>青蚨金融</a>");
document.writeln("						<a href=\'catering.html\'>青蚨餐饮</a>");
document.writeln("						<a href=\'community.html\'>青蚨社区</a>");
document.writeln("						<a href=\'education.html\'>青蚨教育</a>");
document.writeln("						<a href=\'movie.html\'>青蚨影视</a>");
document.writeln("						<a href=\'health.html\'>青蚨健康</a>");
document.writeln("						<a href=\'gongyi.html\'>青蚨公益</a>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'javaScript:;\'>集团动态</a>");
document.writeln("					<i class=\'ico\'></i>");
document.writeln("					<div class=\'menuson\'>");
document.writeln("						<a href=\'gonggao.html\'>重要公告</a>");
document.writeln("						<a href=\'dongtai.html\'>集团动态</a>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'duty.html\'>企业公民</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'connect.html\'>联系我们</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</header>");